### ISSUE TITLE
restcomm JSS7 SCTP

### ISSUE THREAD

**Issue by javad272** [RestComm/jss7#132]
Hi Gents

I get the following error while starting my AS
would you help

14:29:42,373 ERROR [org.mobicents.protocols.ss7.m3ua.impl.oam.SCTPShellExecutor] Error while executing comand [sctp, server, start, Test]: java.lang.UnsupportedOperationException: libsctp.so.1: cannot open shared object file: No such file or directory
        at sun.nio.ch.sctp.SctpNet.socket0(Native Method) [:1.8.0_65]
        at sun.nio.ch.sctp.SctpNet.socket(SctpNet.java:85) [:1.8.0_65]
        at sun.nio.ch.sctp.SctpServerChannelImpl.<init>(SctpServerChannelImpl.java:98) [:1.8.0_65]
        at com.sun.nio.sctp.SctpServerChannel.open(SctpServerChannel.java:102) [:1.8.0_65]
        at org.mobicents.protocols.sctp.ServerImpl.doInitSocketSctp(ServerImpl.java:178) [:1.7.8]
        at org.mobicents.protocols.sctp.ServerImpl.initSocket(ServerImpl.java:157) [:1.7.8]
        at org.mobicents.protocols.sctp.ServerImpl.start(ServerImpl.java:112) [:1.7.8]
        at org.mobicents.protocols.sctp.ManagementImpl.startServer(ManagementImpl.java:647) [:1.7.8]
        at org.mobicents.protocols.ss7.m3ua.impl.oam.SCTPShellExecutor.execute(SCTPShellExecutor.java:313) [:7.0.1383]
        at org.mobicents.ss7.management.console.ShellServer.perform(ShellServer.java:266) [:7.0.1383]
        at org.mobicents.protocols.ss7.scheduler.Task.run(Task.java:108) [:7.0.1383]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745) [:1.8.0_65]

**Comment by vetss** [comment]
Hello @javad272 

Your problem is like you have not installed libsctp lib or have some OS level problems with sctp lib

You can also ask for your problem at a public forum: 
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/mobicents-public/topics

**Comment by javad272** [comment]
Dear Sergey

sorry for my comment in a wrong place and thanks for guiding me

**Comment by vetss** [comment]
I am closing this issue
