### ISSUE TITLE
Support for HEX digits for SCCP GT

### ISSUE THREAD

**Issue by vetss** [RestComm/jss7#134]
SCCP GT supports now only digital values for digits (as for SCCP spec).

We need also add a support for hex digits A-F.
For this we need to update org.mobicents.protocols.ss7.sccp.impl.parameter.DefaultEncodingScheme
methods:
encode() and decode()

Here is an Exception when we want to encode GT String like "111CC111":

2016-06-13 14:47:26,703 ERROR [org.mobicents.protocols.ss7.sccp.impl.SccpStackImpl-SccpStack](SLEE-EventRouterExecutor-7451-thread-1) IOException when sending the message to MTP3 level: For input string: "C"
java.lang.NumberFormatException: For input string: "C"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:492)
    at java.lang.Integer.parseInt(Integer.java:527)
    at org.mobicents.protocols.ss7.sccp.impl.parameter.DefaultEncodingScheme.encode(DefaultEncodingScheme.java:84)
    at org.mobicents.protocols.ss7.sccp.impl.parameter.GlobalTitle0100Impl.encode(GlobalTitle0100Impl.java:131)
    at org.mobicents.protocols.ss7.sccp.impl.parameter.SccpAddressImpl.encode(SccpAddressImpl.java:261)
    at org.mobicents.protocols.ss7.sccp.impl.parameter.SccpAddressImpl.encode(SccpAddressImpl.java:276)
    at org.mobicents.protocols.ss7.sccp.impl.message.SccpDataNoticeTemplateMessageImpl.encode(SccpDataNoticeTemplateMessageImpl.java:305)
    at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.send(SccpRoutingControl.java:220)
    at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.sendMessageToMtp(SccpRoutingControl.java:722)
    at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.route(SccpRoutingControl.java:660)
    at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.translationFunction(SccpRoutingControl.java:462)
    at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.route(SccpRoutingControl.java:710)
    at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.routeMssgFromSccpUser(SccpRoutingControl.java:190)
    at org.mobicents.protocols.ss7.sccp.impl.SccpStackImpl.send(SccpStackImpl.java:507)
    at org.mobicents.protocols.ss7.sccp.impl.SccpProviderImpl.send(SccpProviderImpl.java:144)
    at org.mobicents.protocols.ss7.tcap.TCAPProviderImpl.send(TCAPProviderImpl.java:303)
    at org.mobicents.protocols.ss7.tcap.DialogImpl.send(DialogImpl.java:562)
    at org.mobicents.protocols.ss7.map.MAPProviderImpl.fireTCBegin(MAPProviderImpl.java:1793)
    at org.mobicents.protocols.ss7.map.MAPDialogImpl.send(MAPDialogImpl.java:353)
    at org.mobicents.slee.resource.map.wrappers.MAPDialogWrapper.send(MAPDialogWrapper.java:185)

**Comment by vetss** [comment]
This is the update for sorting out of SCCP GT encoding staff:
https://github.com/RestComm/jss7/commit/7da9d780aa34d54aecb532104728ff12bbb48f9b

I am waiting for testing results.
