### ISSUE TITLE
sccp rule show, sccp rule modify is not working

### ISSUE THREAD

**Issue by nhanth87** [RestComm/jss7#155]
With the latest code of jss7, sccp rule show, sccp rule modify and sccp address show is not working anymore

```
2016-08-03 17:37:51,621 INFO [com.telscale.ss7.management.console.ShellServer] (pool-29-thread-8) received command : sccp rule show 
2016-08-03 17:37:51,624 ERROR [com.telscale.ss7.management.console.ShellServer] (pool-29-thread-1) Exception while operating on ChannelSelectionKey. Client CLI connection will be closed now 
java.nio.BufferOverflowException 
at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:357) 
at java.nio.ByteBuffer.put(ByteBuffer.java:832) 
at org.mobicents.ss7.management.transceiver.Message.encode(Message.java:73) 
at org.mobicents.ss7.management.transceiver.ShellChannel.doWrite(ShellChannel.java:197) 
at org.mobicents.ss7.management.transceiver.ChannelSelector.selectNow(ChannelSelector.java:124) 
at com.telscale.ss7.management.console.ShellServer.perform(ShellServer.java:186) 
at org.mobicents.protocols.ss7.scheduler.Task.run(Task.java:108) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
at java.lang.Thread.run(Thread.java:745)

```

**Comment by vetss** [comment]
@nhanth87 

I think this issue is the same as https://github.com/RestComm/jss7/issues/17

**Comment by nhanth87** [comment]
yes @vetss it's the same at #17, so I close it now

**Comment by vetss** [comment]
@nhanth87  you can investigate #17 :)
