### ISSUE TITLE
Create new LMR rule on the web

### ISSUE THREAD

**Issue by SummaNetworks** [RestComm/jss7#156]
When trying to create a new LMR rule on the web, the following exception is thrown:
17:41:39:430 [ERROR] java.lang.IllegalArgumentException : No enum constant org.mobicents.protocols.ss7.sccp.LongMessageRuleType.LongMessagesForbidden. (Full Stack Trace)

**Comment by vetss** [comment]
ok, I can reproduce the error.

1) The excepition Trace is: 
java.lang.IllegalArgumentException: No enum constant org.mobicents.protocols.ss7.sccp.LongMessageRuleType.XudtEnabled
	at java.lang.Enum.valueOf(Enum.java:236)
	at org.jolokia.converter.object.StringToObjectConverter.prepareValue(StringToObjectConverter.java:124)
	at org.jolokia.converter.object.StringToObjectConverter.prepareValue(StringToObjectConverter.java:101)
	at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:93)
	at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:40)
	at org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:87)
	at org.jolokia.backend.MBeanServerExecutorLocal.handleRequest(MBeanServerExecutorLocal.java:139)
	at org.jolokia.backend.MBeanServerHandler.dispatchRequest(MBeanServerHandler.java:101)
	at org.jolokia.backend.LocalRequestDispatcher.dispatchRequest(LocalRequestDispatcher.java:90)
	at org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:377)
	at org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:147)
	at org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:195)
	at org.jolokia.http.HttpRequestHandler.handleGetRequest(HttpRequestHandler.java:86)
	at org.jolokia.http.AgentServlet$3.handleRequest(AgentServlet.java:293)
	at org.jolokia.http.AgentServlet.handle(AgentServlet.java:225)
	at org.jolokia.http.AgentServlet.doGet(AgentServlet.java:190)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:190)
	at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:92)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(SecurityContextEstablishmentValve.java:126)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:70)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:598)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
	at java.lang.Thread.run(Thread.java:745)

2) The wrong message in GUI creating form:
"Load Sharing Algorithm"

3) Let's check also GUI editing part.

**Comment by knosach** [comment]
already fixed in https://github.com/RestComm/jss7/issues/52
