### ISSUE TITLE
UnknownTransitionException

### ISSUE THREAD

**Issue by jeenareload** [RestComm/jss7#160]
Hi,

I have deploy jss7 stack, after that I have created association, and then trying to connect with local simulator,
I am getting following exception in log, I have captured tshark dump, but found nothing wrong in tshark dump, I am attaching tshark dump,

also can you please tell me why it showing warning. (Rx : MTP-RESUME: AffectedDpc=2020).

[trace.zip](https://github.com/RestComm/jss7/files/443993/trace.zip)

09:40:28,072 ERROR [AspTrafficMaintenanceHandler] Transition=aspactive. FSM.name=ApplicationServer_IPSP_LOCAL old state=DOWN, current state=DOWN
org.mobicents.protocols.ss7.m3ua.impl.fsm.UnknownTransitionException: Transition=aspactive. FSM.name=ApplicationServer_IPSP_LOCAL old state=DOWN, current state=DOWN
        at org.mobicents.protocols.ss7.m3ua.impl.fsm.FSMState.signal(FSMState.java:130)
        at org.mobicents.protocols.ss7.m3ua.impl.fsm.FSM.signal(FSM.java:152)
        at org.mobicents.protocols.ss7.m3ua.impl.AspTrafficMaintenanceHandler.handleAspActive(AspTrafficMaintenanceHandler.java:154)
        at org.mobicents.protocols.ss7.m3ua.impl.AspTrafficMaintenanceHandler.handleAspActive(AspTrafficMaintenanceHandler.java:199)
        at org.mobicents.protocols.ss7.m3ua.impl.AspFactoryImpl.read(AspFactoryImpl.java:420)
        at org.mobicents.protocols.ss7.m3ua.impl.AspFactoryImpl.onPayload(AspFactoryImpl.java:731)
        at org.mobicents.protocols.sctp.AssociationImpl.read(AssociationImpl.java:492)
        at org.mobicents.protocols.sctp.SelectorThread.read(SelectorThread.java:431)
        at org.mobicents.protocols.sctp.SelectorThread.run(SelectorThread.java:155)
        at java.lang.Thread.run(Thread.java:745)
09:40:28,173 WARN  [SccpStackImpl-SccpStack] Rx : MTP-RESUME: AffectedDpc=2020
09:40:52,456 INFO  [SccpManagement-SccpStack] Rx : SSA, Affected SSN=6, Affected PC=2020, Subsystem Multiplicity Ind=0 SeqControl=0

**Comment by nhanth87** [comment]
Hi Jeen,
Please open ticket on https://groups.google.com/forum/#!forum/mobicents-public for this issue

Br,
TN
