### ISSUE TITLE
Deadlock when we are deploying messages into the same host

### ISSUE THREAD

**Issue by vetss** [RestComm/jss7#175]
We can have a deadlock when we are delivering a message into the stack messages that were originated from the same stack.

We need to schedule such local invokes into some ThreadScheduler task instead of direct invoking of listner in "SccpRoutingControl.route(SccpAddressedMessageImpl msg)" line
"listener.onMessage((SccpDataMessage) msg);"

Threads stack:

Java stack information for the threads listed above:

"pool-43-thread-1":
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x000000075018f380> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:867)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1197)
at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:214)
at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:290)
at org.mobicents.protocols.ss7.tcap.DialogImpl.processAbort(DialogImpl.java:1701)
at org.mobicents.protocols.ss7.tcap.TCAPProviderImpl.onMessage(TCAPProviderImpl.java:774)
at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.route(SccpRoutingControl.java:558)
at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.routeMssgFromSccpUser(SccpRoutingControl.java:190)
at org.mobicents.protocols.ss7.sccp.impl.SccpStackImpl.send(SccpStackImpl.java:507)
at org.mobicents.protocols.ss7.sccp.impl.SccpProviderImpl.send(SccpProviderImpl.java:144)
at org.mobicents.protocols.ss7.tcap.TCAPProviderImpl.send(TCAPProviderImpl.java:303)
at org.mobicents.protocols.ss7.tcap.DialogImpl.send(DialogImpl.java:970)
at org.mobicents.slee.resource.tcap.wrappers.TCAPDialogWrapper.send(TCAPDialogWrapper.java:375)
at .......

"pool-41-thread-1":
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x000000074b087678> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:867)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1197)
at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:214)
at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:290)
at org.mobicents.protocols.ss7.tcap.DialogImpl.processEnd(DialogImpl.java:1623)
at org.mobicents.protocols.ss7.tcap.TCAPProviderImpl.onMessage(TCAPProviderImpl.java:744)
at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.route(SccpRoutingControl.java:558)
at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.routeMssgFromSccpUser(SccpRoutingControl.java:190)
at org.mobicents.protocols.ss7.sccp.impl.SccpStackImpl.send(SccpStackImpl.java:507)
at org.mobicents.protocols.ss7.sccp.impl.SccpProviderImpl.send(SccpProviderImpl.java:144)
at org.mobicents.protocols.ss7.tcap.TCAPProviderImpl.send(TCAPProviderImpl.java:303)
at org.mobicents.protocols.ss7.tcap.DialogImpl.send(DialogImpl.java:800)
at org.mobicents.slee.resource.tcap.wrappers.TCAPDialogWrapper.send(TCAPDialogWrapper.java:363)
at ...............

Found 1 deadlock.

**Comment by jaimecasero** [comment]
If there are a number of locks to be acquired, the stack needs to enforce all the scenarios acquire those locks in the same order to prevent deadlocks. Otherwise, it could be potentially delegated to a threadpool with dialog affinity, so locks are acquired by the same thread, while next activity needs to wait the running thread to complete.

**Comment by vetss** [comment]
Thanks @jaimecasero for a comment.
I understand the reason for this concrete case and need to fix it.

**Comment by vetss** [comment]
Fixing by:

https://github.com/RestComm/jss7/commit/8e0f3dda3789f0b65dd4be1781d4560c87b1cedc
