### ISSUE TITLE
jss7-management-console issue

### ISSUE THREAD

**Issue by Osklizg** [RestComm/jss7#237]
I would like to ask for help, i have installed the Resctomm SS7Stack (download restcomm-jss7-7.2.1390.zip). I can open the GUI but i have errors.
My OS is Ubuntu 14.04. 
jolokia write: {"timestamp":1495096202,"status":200,"request":{"type":"version"},"value":{"protocol":"7.0","agent":"1.1.0","info":{"product":"jboss","vendor":"RedHat","version":"5.0.0.GA"}}}

java version "1.6.0_31"
OpenJDK Runtime Environment (IcedTea6 1.13.3) (6b31-1.13.3-1ubuntu1)
OpenJDK Client VM (build 23.25-b01, mixed mode, sharing)

 JBoss Bootstrap Environment

  JBOSS_HOME: /usr/local/share/jboss/

  JAVA: java

  JAVA_OPTS: -Dprogram.name=run.sh -Xms128m -Xmx512m -XX:MaxPermSize=256m -Dorg.jboss.resolver.warning=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djava.net.preferIPv4Stack=true

  CLASSPATH: /usr/local/share/jboss//bin/run.jar

=========================================================================

11:22:42,503 INFO  [ServerImpl] Starting JBoss (Microcontainer)...
11:22:42,505 INFO  [ServerImpl] Release ID: JBoss [Morpheus] 5.0.0.GA (build: SVNTag=JBoss_5_0_0_GA date=200812041714)
11:22:42,505 INFO  [ServerImpl] Bootstrap URL: null
11:22:42,505 INFO  [ServerImpl] Home Dir: /usr/local/share/jboss
11:22:42,505 INFO  [ServerImpl] Home URL: file:/usr/local/share/jboss/
11:22:42,506 INFO  [ServerImpl] Library URL: file:/usr/local/share/jboss/lib/
11:22:42,506 INFO  [ServerImpl] Patch URL: null
11:22:42,506 INFO  [ServerImpl] Common Base URL: file:/usr/local/share/jboss/common/
11:22:42,506 INFO  [ServerImpl] Common Library URL: file:/usr/local/share/jboss/common/lib/
11:22:42,507 INFO  [ServerImpl] Server Name: default
11:22:42,507 INFO  [ServerImpl] Server Base Dir: /usr/local/share/jboss/server
11:22:42,507 INFO  [ServerImpl] Server Base URL: file:/usr/local/share/jboss/server/
11:22:42,507 INFO  [ServerImpl] Server Config URL: file:/usr/local/share/jboss/server/default/conf/
11:22:42,507 INFO  [ServerImpl] Server Home Dir: /usr/local/share/jboss/server/default
11:22:42,508 INFO  [ServerImpl] Server Home URL: file:/usr/local/share/jboss/server/default/
11:22:42,508 INFO  [ServerImpl] Server Data Dir: /usr/local/share/jboss/server/default/data
11:22:42,508 INFO  [ServerImpl] Server Library URL: file:/usr/local/share/jboss/server/default/lib/
11:22:42,508 INFO  [ServerImpl] Server Log Dir: /usr/local/share/jboss/server/default/log
11:22:42,508 INFO  [ServerImpl] Server Native Dir: /usr/local/share/jboss/server/default/tmp/native
11:22:42,508 INFO  [ServerImpl] Server Temp Dir: /usr/local/share/jboss/server/default/tmp
11:22:42,509 INFO  [ServerImpl] Server Temp Deploy Dir: /usr/local/share/jboss/server/default/tmp/deploy
11:22:43,081 INFO  [ServerImpl] Starting Microcontainer, bootstrapURL=file:/usr/local/share/jboss/server/default/conf/bootstrap.xml
11:22:43,475 INFO  [VFSCacheFactory] Initializing VFSCache [org.jboss.virtual.plugins.cache.IterableTimedVFSCache]
11:22:43,482 INFO  [VFSCacheFactory] Using VFSCache [IterableTimedVFSCache{lifetime=1800, resolution=60}]
11:22:43,744 INFO  [CopyMechanism] VFS temp dir: /usr/local/share/jboss/server/default/tmp
11:22:43,746 INFO  [ZipEntryContext] VFS force nested jars copy-mode is enabled.
11:22:44,681 INFO  [ServerInfo] Java version: 1.6.0_31,Sun Microsystems Inc.
11:22:44,681 INFO  [ServerInfo] Java VM: OpenJDK Client VM 23.25-b01,Sun Microsystems Inc.
11:22:44,682 INFO  [ServerInfo] OS-System: Linux 3.16.0-30-generic,i386
11:22:44,748 INFO  [JMXKernel] Legacy JMX core initialized
11:22:46,038 INFO  [ProfileServiceImpl] Loading profile: default from: org.jboss.system.server.profileservice.repository.SerializableDeploymentRepository@1454f66(root=/usr/local/share/jboss/server, key=org.jboss.profileservice.spi.ProfileKey@143b82c3[domain=default,server=default,name=default])
11:22:46,044 INFO  [ProfileImpl] Using repository:org.jboss.system.server.profileservice.repository.SerializableDeploymentRepository@1454f66(root=/usr/local/share/jboss/server, key=org.jboss.profileservice.spi.ProfileKey@143b82c3[domain=default,server=default,name=default])
11:22:46,044 INFO  [ProfileServiceImpl] Loaded profile: ProfileImpl@6f7e0a{key=org.jboss.profileservice.spi.ProfileKey@143b82c3[domain=default,server=default,name=default]}
11:22:47,096 INFO  [WebService] Using RMI server codebase: http://172.27.27.85:8083/
11:22:51,615 INFO  [NativeServerConfig] JBoss Web Services - Stack Native Core
11:22:51,615 INFO  [NativeServerConfig] 3.0.4.SP1
11:22:59,294 INFO  [JMXConnectorServerService] JMX Connector server: service:jmx:rmi://172.27.27.85/jndi/rmi://172.27.27.85:1090/jmxconnector
11:22:59,398 INFO  [MailService] Mail Service bound to java:/Mail
11:23:00,691 WARN  [JBossASSecurityMetadataStore] WARNING! POTENTIAL SECURITY RISK. It has been detected that the MessageSucker component which sucks messages from one node to another has not had its password changed from the installation default. Please see the JBoss Messaging user guide for instructions on how to do this.
11:23:00,746 WARN  [AnnotationCreator] No ClassLoader provided, using TCCL: org.jboss.managed.api.annotation.ManagementComponent
11:23:00,894 INFO  [TransactionManagerService] JBossTS Transaction Service (JTA version) - JBoss Inc.
11:23:00,895 INFO  [TransactionManagerService] Setting up property manager MBean and JMX layer
11:23:01,055 INFO  [TransactionManagerService] Initializing recovery manager
11:23:01,142 INFO  [TransactionManagerService] Recovery manager configured
11:23:01,142 INFO  [TransactionManagerService] Binding TransactionManager JNDI Reference
11:23:01,161 INFO  [TransactionManagerService] Starting transaction recovery manager
11:23:02,128 INFO  [Http11Protocol] Initializing Coyote HTTP/1.1 on http-172.27.27.85-8089
11:23:02,129 INFO  [AjpProtocol] Initializing Coyote AJP/1.3 on ajp-172.27.27.85-8009
11:23:02,129 INFO  [StandardService] Starting service jboss.web
11:23:02,131 INFO  [StandardEngine] Starting Servlet Engine: JBoss Web/2.1.1.GA
11:23:02,180 INFO  [Catalina] Server startup in 122 ms
11:23:02,197 INFO  [TomcatDeployment] deploy, ctxPath=/invoker, vfsUrl=http-invoker.sar/invoker.war
11:23:02,617 INFO  [TomcatDeployment] deploy, ctxPath=/jbossws, vfsUrl=jbossws.sar/jbossws-management.war
11:23:02,650 INFO  [TomcatDeployment] deploy, ctxPath=/web-console, vfsUrl=management/console-mgr.sar/web-console.war
11:23:02,910 INFO  [RARDeployment] Required license terms exist, view vfszip:/usr/local/share/jboss/server/default/deploy/jboss-local-jdbc.rar/META-INF/ra.xml
11:23:02,925 INFO  [RARDeployment] Required license terms exist, view vfszip:/usr/local/share/jboss/server/default/deploy/jboss-xa-jdbc.rar/META-INF/ra.xml
11:23:02,947 INFO  [RARDeployment] Required license terms exist, view vfszip:/usr/local/share/jboss/server/default/deploy/jms-ra.rar/META-INF/ra.xml
11:23:02,965 INFO  [RARDeployment] Required license terms exist, view vfszip:/usr/local/share/jboss/server/default/deploy/mail-ra.rar/META-INF/ra.xml
11:23:03,031 INFO  [RARDeployment] Required license terms exist, view vfszip:/usr/local/share/jboss/server/default/deploy/quartz-ra.rar/META-INF/ra.xml
11:23:03,097 INFO  [SimpleThreadPool] Job execution threads will use class loader of thread: main
11:23:03,116 INFO  [QuartzScheduler] Quartz Scheduler v.1.5.2 created.
11:23:03,119 INFO  [RAMJobStore] RAMJobStore initialized.
11:23:03,119 INFO  [StdSchedulerFactory] Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
11:23:03,119 INFO  [StdSchedulerFactory] Quartz scheduler version: 1.5.2
11:23:03,120 INFO  [QuartzScheduler] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
11:23:04,044 INFO  [ConnectionFactoryBindingService] Bound ConnectionManager 'jboss.jca:service=DataSourceBinding,name=DefaultDS' to JNDI name 'java:DefaultDS'
11:23:04,247 WARN  [QuartzTimerServiceFactory] sql failed: CREATE TABLE QRTZ_JOB_DETAILS(JOB_NAME VARCHAR(80) NOT NULL, JOB_GROUP VARCHAR(80) NOT NULL, DESCRIPTION VARCHAR(120) NULL, JOB_CLASS_NAME VARCHAR(128) NOT NULL, IS_DURABLE VARCHAR(1) NOT NULL, IS_VOLATILE VARCHAR(1) NOT NULL, IS_STATEFUL VARCHAR(1) NOT NULL, REQUESTS_RECOVERY VARCHAR(1) NOT NULL, JOB_DATA BINARY NULL, PRIMARY KEY (JOB_NAME,JOB_GROUP))
11:23:04,281 INFO  [SimpleThreadPool] Job execution threads will use class loader of thread: main
11:23:04,283 INFO  [QuartzScheduler] Quartz Scheduler v.1.5.2 created.
11:23:04,283 INFO  [JobStoreCMT] Using db table-based data access locking (synchronization).
11:23:04,290 INFO  [JobStoreCMT] Removed 0 Volatile Trigger(s).
11:23:04,290 INFO  [JobStoreCMT] Removed 0 Volatile Job(s).
11:23:04,290 INFO  [JobStoreCMT] JobStoreCMT initialized.
11:23:04,290 INFO  [StdSchedulerFactory] Quartz scheduler 'JBossEJB3QuartzScheduler' initialized from an externally provided properties instance.
11:23:04,291 INFO  [StdSchedulerFactory] Quartz scheduler version: 1.5.2
11:23:04,296 INFO  [JobStoreCMT] Freed 0 triggers from 'acquired' / 'blocked' state.
11:23:04,297 INFO  [JobStoreCMT] Recovering 0 jobs that were in-progress at the time of the last shut-down.
11:23:04,297 INFO  [JobStoreCMT] Recovery complete.
11:23:04,298 INFO  [JobStoreCMT] Removed 0 'complete' triggers.
11:23:04,298 INFO  [JobStoreCMT] Removed 0 stale fired job entries.
11:23:04,303 INFO  [QuartzScheduler] Scheduler JBossEJB3QuartzScheduler_$_NON_CLUSTERED started.
11:23:04,455 INFO  [ServerPeer] JBoss Messaging 1.4.1.GA server [0] started
11:23:04,573 INFO  [ConnectionFactory] Connector bisocket://172.27.27.85:4457 has leasing enabled, lease period 10000 milliseconds
11:23:04,573 INFO  [ConnectionFactory] org.jboss.jms.server.connectionfactory.ConnectionFactory@1915cb4 started
11:23:04,586 INFO  [QueueService] Queue[/queue/DLQ] started, fullSize=200000, pageSize=2000, downCacheSize=2000
11:23:04,588 INFO  [QueueService] Queue[/queue/ExpiryQueue] started, fullSize=200000, pageSize=2000, downCacheSize=2000
11:23:04,589 INFO  [ConnectionFactory] Connector bisocket://172.27.27.85:4457 has leasing enabled, lease period 10000 milliseconds
11:23:04,589 INFO  [ConnectionFactory] org.jboss.jms.server.connectionfactory.ConnectionFactory@1b7e7b5 started
11:23:04,589 WARN  [ConnectionFactoryJNDIMapper] supportsFailover attribute is true on connection factory: jboss.messaging.connectionfactory:service=ClusteredConnectionFactory but post office is non clustered. So connection factory will *not* support failover
11:23:04,590 WARN  [ConnectionFactoryJNDIMapper] supportsLoadBalancing attribute is true on connection factory: jboss.messaging.connectionfactory:service=ClusteredConnectionFactory but post office is non clustered. So connection factory will *not* support load balancing
11:23:04,592 INFO  [ConnectionFactory] Connector bisocket://172.27.27.85:4457 has leasing enabled, lease period 10000 milliseconds
11:23:04,592 INFO  [ConnectionFactory] org.jboss.jms.server.connectionfactory.ConnectionFactory@e37430 started
11:23:04,699 INFO  [ConnectionFactoryBindingService] Bound ConnectionManager 'jboss.jca:service=ConnectionFactoryBinding,name=JmsXA' to JNDI name 'java:JmsXA'
11:23:04,713 INFO  [TomcatDeployment] deploy, ctxPath=/, vfsUrl=ROOT.war
11:23:04,751 INFO  [TomcatDeployment] deploy, ctxPath=/jmx-console, vfsUrl=jmx-console.war
11:23:04,801 INFO  [TomcatDeployment] deploy, ctxPath=/jolokia, vfsUrl=jolokia.war
11:23:04,833 INFO  [[/jolokia]] jolokia-agent: No access restrictor found at classpath:/jolokia-access.xml, access to all MBeans is allowed
11:23:05,069 INFO  [TomcatDeployment] deploy, ctxPath=/jss7-management-console, vfsUrl=jss7-management-console.war
11:23:05,833 WARN  [ClassLoaderManager] Unexpected error during load of:org.mobicents.protocols.sctp.ManagementImpl
java.lang.UnsupportedClassVersionError: org/mobicents/protocols/sctp/ManagementImpl : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
        at org.jboss.classloader.spi.base.BaseClassLoader.access$200(BaseClassLoader.java:62)
        at org.jboss.classloader.spi.base.BaseClassLoader$2.run(BaseClassLoader.java:509)
        at org.jboss.classloader.spi.base.BaseClassLoader$2.run(BaseClassLoader.java:469)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.jboss.classloader.spi.base.BaseClassLoader.loadClassLocally(BaseClassLoader.java:467)
        at org.jboss.classloader.spi.base.BaseClassLoader.loadClassLocally(BaseClassLoader.java:444)
        at org.jboss.classloader.spi.base.BaseDelegateLoader.loadClass(BaseDelegateLoader.java:134)
        at org.jboss.classloader.spi.filter.FilteredDelegateLoader.loadClass(FilteredDelegateLoader.java:131)
        at org.jboss.classloader.spi.base.ClassLoadingTask$ThreadTask.run(ClassLoadingTask.java:452)
        at org.jboss.classloader.spi.base.ClassLoaderManager.nextTask(ClassLoaderManager.java:254)
        at org.jboss.classloader.spi.base.ClassLoaderManager.process(ClassLoaderManager.java:148)
        at org.jboss.classloader.spi.base.BaseClassLoaderDomain.loadClass(BaseClassLoaderDomain.java:256)
        at org.jboss.classloader.spi.base.BaseClassLoaderDomain.loadClass(BaseClassLoaderDomain.java:1099)
        at org.jboss.classloader.spi.base.BaseClassLoader.loadClassFromDomain(BaseClassLoader.java:735)
        at org.jboss.classloader.spi.base.BaseClassLoader.loadClass(BaseClassLoader.java:378)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
        at org.jboss.deployers.vfs.deployer.kernel.BeanMetaDataFactoryVisitor.addBeanComponent(BeanMetaDataFactoryVisitor.java:63)
        at org.jboss.deployers.vfs.deployer.kernel.BeanMetaDataFactoryVisitor.deploy(BeanMetaDataFactoryVisitor.java:126)
        at org.jboss.deployers.spi.deployer.helpers.AbstractRealDeployerWithInput.deploy(AbstractRealDeployerWithInput.java:125)
        at org.jboss.deployers.spi.deployer.helpers.AbstractRealDeployerWithInput.internalDeploy(AbstractRealDeployerWithInput.java:102)
        at org.jboss.deployers.spi.deployer.helpers.AbstractComponentDeployer.internalDeploy(AbstractComponentDeployer.java:78)
        at org.jboss.deployers.spi.deployer.helpers.AbstractRealDeployer.deploy(AbstractRealDeployer.java:50)
        at org.jboss.deployers.plugins.deployers.DeployerWrapper.deploy(DeployerWrapper.java:171)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.doDeploy(DeployersImpl.java:1439)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.doInstallParentFirst(DeployersImpl.java:1157)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.install(DeployersImpl.java:1098)
        at org.jboss.dependency.plugins.AbstractControllerContext.install(AbstractControllerContext.java:348)
        at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:1598)
        at org.jboss.dependency.plugins.AbstractController.incrementState(AbstractController.java:934)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:1062)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:984)
        at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:822)
        at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:553)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.process(DeployersImpl.java:781)
        at org.jboss.deployers.plugins.main.MainDeployerImpl.process(MainDeployerImpl.java:545)
        at org.jboss.system.server.profileservice.ProfileServiceBootstrap.loadProfile(ProfileServiceBootstrap.java:304)
        at org.jboss.system.server.profileservice.ProfileServiceBootstrap.start(ProfileServiceBootstrap.java:205)
        at org.jboss.bootstrap.AbstractServerImpl.start(AbstractServerImpl.java:405)
        at org.jboss.Main.boot(Main.java:209)
        at org.jboss.Main$1.run(Main.java:547)
        at java.lang.Thread.run(Thread.java:701)
11:23:05,840 ERROR [AbstractKernelController] Error installing to Real: name=vfsfile:/usr/local/share/jboss/server/default/deploy/restcomm-ss7-service/META-INF/jboss-beans.xml state=PreReal mode=Manual requiredState=Real
org.jboss.deployers.spi.DeploymentException: Error deploying: vfsfile:/usr/local/share/jboss/server/default/deploy/restcomm-ss7-service/META-INF/jboss-beans.xml
        at org.jboss.deployers.spi.DeploymentException.rethrowAsDeploymentException(DeploymentException.java:49)
        at org.jboss.deployers.vfs.deployer.kernel.BeanMetaDataFactoryVisitor.deploy(BeanMetaDataFactoryVisitor.java:136)
        at org.jboss.deployers.spi.deployer.helpers.AbstractRealDeployerWithInput.deploy(AbstractRealDeployerWithInput.java:125)
        at org.jboss.deployers.spi.deployer.helpers.AbstractRealDeployerWithInput.internalDeploy(AbstractRealDeployerWithInput.java:102)
        at org.jboss.deployers.spi.deployer.helpers.AbstractComponentDeployer.internalDeploy(AbstractComponentDeployer.java:78)
        at org.jboss.deployers.spi.deployer.helpers.AbstractRealDeployer.deploy(AbstractRealDeployer.java:50)
        at org.jboss.deployers.plugins.deployers.DeployerWrapper.deploy(DeployerWrapper.java:171)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.doDeploy(DeployersImpl.java:1439)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.doInstallParentFirst(DeployersImpl.java:1157)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.install(DeployersImpl.java:1098)
        at org.jboss.dependency.plugins.AbstractControllerContext.install(AbstractControllerContext.java:348)
        at org.jboss.dependency.plugins.AbstractController.install(AbstractController.java:1598)
        at org.jboss.dependency.plugins.AbstractController.incrementState(AbstractController.java:934)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:1062)
        at org.jboss.dependency.plugins.AbstractController.resolveContexts(AbstractController.java:984)
        at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:822)
        at org.jboss.dependency.plugins.AbstractController.change(AbstractController.java:553)
        at org.jboss.deployers.plugins.deployers.DeployersImpl.process(DeployersImpl.java:781)
        at org.jboss.deployers.plugins.main.MainDeployerImpl.process(MainDeployerImpl.java:545)
        at org.jboss.system.server.profileservice.ProfileServiceBootstrap.loadProfile(ProfileServiceBootstrap.java:304)
        at org.jboss.system.server.profileservice.ProfileServiceBootstrap.start(ProfileServiceBootstrap.java:205)
        at org.jboss.bootstrap.AbstractServerImpl.start(AbstractServerImpl.java:405)
        at org.jboss.Main.boot(Main.java:209)
        at org.jboss.Main$1.run(Main.java:547)
        at java.lang.Thread.run(Thread.java:701)
Caused by: java.lang.IllegalArgumentException: Exception loading class for ScopeKey addition.
        at org.jboss.deployers.vfs.deployer.kernel.BeanMetaDataFactoryVisitor.addBeanComponent(BeanMetaDataFactoryVisitor.java:67)
        at org.jboss.deployers.vfs.deployer.kernel.BeanMetaDataFactoryVisitor.deploy(BeanMetaDataFactoryVisitor.java:126)
        ... 23 more
Caused by: java.lang.ClassNotFoundException: Unexpected error during load of: org.mobicents.protocols.sctp.ManagementImpl, msg=org/mobicents/protocols/sctp/ManagementImpl : Unsupported major.minor version 51.0
        at org.jboss.classloader.spi.base.ClassLoaderManager.process(ClassLoaderManager.java:169)
        at org.jboss.classloader.spi.base.BaseClassLoaderDomain.loadClass(BaseClassLoaderDomain.java:256)
        at org.jboss.classloader.spi.base.BaseClassLoaderDomain.loadClass(BaseClassLoaderDomain.java:1099)
        at org.jboss.classloader.spi.base.BaseClassLoader.loadClassFromDomain(BaseClassLoader.java:735)
        at org.jboss.classloader.spi.base.BaseClassLoader.loadClass(BaseClassLoader.java:378)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
        at org.jboss.deployers.vfs.deployer.kernel.BeanMetaDataFactoryVisitor.addBeanComponent(BeanMetaDataFactoryVisitor.java:63)
        ... 24 more
Caused by: java.lang.UnsupportedClassVersionError: org/mobicents/protocols/sctp/ManagementImpl : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
        at org.jboss.classloader.spi.base.BaseClassLoader.access$200(BaseClassLoader.java:62)
        at org.jboss.classloader.spi.base.BaseClassLoader$2.run(BaseClassLoader.java:509)
        at org.jboss.classloader.spi.base.BaseClassLoader$2.run(BaseClassLoader.java:469)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.jboss.classloader.spi.base.BaseClassLoader.loadClassLocally(BaseClassLoader.java:467)
        at org.jboss.classloader.spi.base.BaseClassLoader.loadClassLocally(BaseClassLoader.java:444)
        at org.jboss.classloader.spi.base.BaseDelegateLoader.loadClass(BaseDelegateLoader.java:134)
        at org.jboss.classloader.spi.filter.FilteredDelegateLoader.loadClass(FilteredDelegateLoader.java:131)
        at org.jboss.classloader.spi.base.ClassLoadingTask$ThreadTask.run(ClassLoadingTask.java:452)
        at org.jboss.classloader.spi.base.ClassLoaderManager.nextTask(ClassLoaderManager.java:254)
        at org.jboss.classloader.spi.base.ClassLoaderManager.process(ClassLoaderManager.java:148)
        ... 30 more
11:23:05,909 ERROR [ProfileServiceBootstrap] Failed to load profile: Summary of incomplete deployments (SEE PREVIOUS ERRORS FOR DETAILS):

*** CONTEXTS IN ERROR: Name -> Error

vfsfile:/usr/local/share/jboss/server/default/deploy/restcomm-ss7-service/META-INF/jboss-beans.xml -> java.lang.UnsupportedClassVersionError: org/mobicents/protocols/sctp/ManagementImpl : Unsupported major.minor version 51.0

11:23:05,918 INFO  [Http11Protocol] Starting Coyote HTTP/1.1 on http-172.27.27.85-8089
11:23:05,933 INFO  [AjpProtocol] Starting Coyote AJP/1.3 on ajp-172.27.27.85-8009
11:23:05,939 INFO  [ServerImpl] JBoss (Microcontainer) [5.0.0.GA (build: SVNTag=JBoss_5_0_0_GA date=200812041714)] Started in 23s:428ms

Thanks in advance

**Comment by tspslegr** [comment]
Hallo, 
try with JDK7 
Pavel

**Comment by ElvisAttro** [comment]
If you want to use jss7 over SCTP, you need jdk 1.7

**Comment by Osklizg** [comment]
Yes, it helped. Thank you!
