### ISSUE TITLE
CLI bug - Exception after long input and the "up arrow" pressing

### ISSUE THREAD

**Issue by vetss** [RestComm/jss7#42]
How to reproduce it:
1) type a big command which is contained in several rows 
like
smpp esme create test2 test2 127.0.0.1 -1 TRANSCEIVER SERVER password test esme-ton -1 esme-npi -1 esme-range 6667 source-range 6667 routing-range 6667 charging-enabled false networkid 1
2) after response from the server - type "uip arrow"
"up arrow"*
3) the I can see:
telscale(local)>Exception in thread "main" java.lang.NumberFormatException: For
input string: "2B"
at java.lang.NumberFormatException.forInputString(NumberFormatException.
java:65)
at java.lang.Integer.parseInt(Integer.java:492)
at java.lang.Integer.<init>(Integer.java:677)
at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:120
)
at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
at java.io.PrintWriter.flush(PrintWriter.java:320)
at org.jboss.jreadline.terminal.WindowsTerminal.write(WindowsTerminal.ja
va:86)
at org.jboss.jreadline.console.Console.drawLine(Console.java:711)
at org.jboss.jreadline.console.Console.redrawLine(Console.java:697)
at org.jboss.jreadline.console.Console.getHistoryElement(Console.java:47
4)
at org.jboss.jreadline.console.Console.read(Console.java:392)
at org.jboss.jreadline.console.Console.read(Console.java:221)
at org.mobicents.ss7.management.console.ConsoleImpl.readLine(ConsoleImpl
.java:235)
at org.mobicents.ss7.management.console.CommandContextImpl.readLine(Comm
andContextImpl.java:290)
at org.mobicents.ss7.management.console.Shell.start(Shell.java:92)
at org.mobicents.ss7.management.console.Shell.main(Shell.java:58)
Для продолжения нажмите любую клавишу . . .
then ss7-cli terminates
and at the server side I can see
14:00:28,837 ERROR [ShellServer](pool-30-thread-6) IO Exception while operating
on ChannelSelectionKey. Client CLI connection will be closed now
java.io.IOException: ╙фрыхээ√щ їюёЄ яЁшэєфшЄхы№эю ЁрчюЁтры ёє∙хёЄтє■∙хх яюфъы■ўх
эшх
at sun.nio.ch.SocketDispatcher.read0(Native Method)
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:225)
at sun.nio.ch.IOUtil.read(IOUtil.java:193)
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:359)
at org.mobicents.ss7.management.transceiver.ShellChannel.doRead(ShellCha
nnel.java:164)
at org.mobicents.ss7.management.transceiver.ChannelSelector.selectNow(Ch
annelSelector.java:116)
at com.telscale.ss7.management.console.ShellServer.perform(ShellServer.j
ava:186)
at org.mobicents.protocols.ss7.scheduler.Task.run(Task.java:108)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
at java.lang.Thread.run(Thread.java:722)

**Comment by olenara** [comment]
@vetss this issue is not reproducable after we implemented changed is #46

**Comment by olenara** [comment]
@vetss please advise how to reproduce it. Closing related Jira JSSSEVEN-237
