### ISSUE TITLE
Dialogic board: GctException: Could not Get GCT message

### ISSUE THREAD

**Issue by vetss** [RestComm/jss7#53]
When a Dialogic board is down or congested (I am not 100% sure that this is a congestion case but may be) we can have the mentioned lower Exception.

The Exception occurs in the method Mtp3UserPartBaseImpl.sendMessage(Mtp3TransferPrimitive msg) in code line:
GctMsg txMsg = GctLib.getm(buf.length);

So it's looks like we have a lack of GctMsg messages to obtain from the board.
How to solve:
- try to get statistic / board state from the board to understand what really happens
- capture Exceptions or / and check a board's state and buffer then unsent messages.
- If too many messages in such case - we will possibly need to care of
  - control of a board state active/prohibited (and generating like MTP-PAUSE)
  - congestion control.

**Comment by vetss** [comment]
2016-03-17 09:38:23,267 ERROR [org.mobicents.protocols.ss7.tcap.DialogImpl] (pool-56-thread-1) Failed to send message:
java.io.IOException: java.io.IOException: com.dialogic.signaling.gct.GctException: Could not Get GCT message
at org.mobicents.protocols.ss7.sccp.impl.SccpProviderImpl.send(SccpProviderImpl.java:146)
at org.mobicents.protocols.ss7.tcap.TCAPProviderImpl.send(TCAPProviderImpl.java:303)
at org.mobicents.protocols.ss7.tcap.DialogImpl.send(DialogImpl.java:562)
at org.mobicents.protocols.ss7.map.MAPProviderImpl.fireTCBegin(MAPProviderImpl.java:1793)
at org.mobicents.protocols.ss7.map.MAPDialogImpl.send(MAPDialogImpl.java:353)
at org.mobicents.slee.resource.map.wrappers.MAPDialogWrapper.send(MAPDialogWrapper.java:185)
at org.mobicents.smsc.slee.services.mt.SriSbb.sendSRI(SriSbb.java:591)
at org.mobicents.smsc.slee.services.mt.SriSbb.onSms(SriSbb.java:185)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.mobicents.slee.runtime.sbbentity.SbbEntityImpl.invokeEventHandler(SbbEntityImpl.java:479)
at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.routeQueuedEvent(EventRoutingTaskImpl.java:379)
at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.run(EventRoutingTaskImpl.java:126)
at org.mobicents.slee.runtime.eventrouter.EventRouterExecutorImpl$EventRoutingTaskStatsCollector.run(EventRouterExecutorImpl.java:76)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: com.dialogic.signaling.gct.GctException: Could not Get GCT message
at org.mobicents.ss7.hardware.dialogic.DialogicMtp3UserPart.sendMessage(DialogicMtp3UserPart.java:122)
at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.send(SccpRoutingControl.java:229)
at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.sendMessageToMtp(SccpRoutingControl.java:722)
at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.route(SccpRoutingControl.java:660)
at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.translationFunction(SccpRoutingControl.java:462)
at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.route(SccpRoutingControl.java:710)
at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.routeMssgFromSccpUser(SccpRoutingControl.java:190)
at org.mobicents.protocols.ss7.sccp.impl.SccpStackImpl.send(SccpStackImpl.java:507)
at org.mobicents.protocols.ss7.sccp.impl.SccpProviderImpl.send(SccpProviderImpl.java:144)
... 18 more
Caused by: com.dialogic.signaling.gct.GctException: Could not Get GCT message
at com.dialogic.signaling.gct.GctLib.getm(GctLib.java:76)
at com.dialogic.signaling.gct.GctLib.getm(GctLib.java:92)
at org.mobicents.ss7.hardware.dialogic.DialogicMtp3UserPart.sendMessage(DialogicMtp3UserPart.java:113)
... 26 more
