### ISSUE TITLE
SCCP - make EncodingScheme classes serializable

### ISSUE THREAD

**Issue by gfigiel** [RestComm/jss7#55]
As EcodingScheme related classes are not serializable this prevents using SccpAddress object as CMP fields which can be usefull for variuou use cases.

SccpAddress objects of RI=GT and GT of type 0010, 0001, 0100 cannot be serializable as they contain BCDOddEncodingScheme type objects: 
2016-03-25 14:19:19,501 ERROR [org.jboss.cache.marshall.CacheMarshaller300] (pool-48-thread-1) Error while marshalling object: (............) key=destinationSccpAddress, value=pc=0,ssn=0,AI=8,gt=GlobalTitle0010Impl [digits=48602009950, translationType=0, encodingScheme=BCDOddEncodingScheme[type=BCD_ODD, code=1]]}
java.io.NotSerializableException: org.mobicents.protocols.ss7.sccp.impl.parameter.BCDOddEncodingScheme
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547) 

I guess it is enough to implement XMLSerializable interface in DefaultEncodingScheme class:
https://github.com/RestComm/jss7/blob/f778660ee09f239121970cf4aca5ca3ee599c580/sccp/sccp-impl/src/main/java/org/mobicents/protocols/ss7/sccp/impl/parameter/DefaultEncodingScheme.java#L36

**Comment by deruelle** [comment]
Thanks @gfigiel for the report. Do you want to contribute and do a Pull request for that ?

**Comment by gfigiel** [comment]
Yes I implemented the change and I am testing it now.

**Comment by deruelle** [comment]
Souds great !

**Comment by vetss** [comment]
I have added your update into master and netty-2 branches
