### ISSUE TITLE
GUI: adding of SCTP object modifying

### ISSUE THREAD

**Issue by vetss** [RestComm/jss7#71]
We need to add apossibility to modify / update of SCTP objects in GUI interface to simplify SCTP stack configuring :
- server
- association

We will be able to fix it only after the issue is fixed: 
https://github.com/RestComm/sctp/issues/15

**Comment by javad272** [comment]
Hi vetss
I get the following error while starting my AS server
would you help?
14:29:42,373 ERROR [org.mobicents.protocols.ss7.m3ua.impl.oam.SCTPShellExecutor] Error while executing comand [sctp, server, start, Test]: java.lang.UnsupportedOperationException: libsctp.so.1: cannot open shared object file: No such file or directory
        at sun.nio.ch.sctp.SctpNet.socket0(Native Method) [:1.8.0_65]
        at sun.nio.ch.sctp.SctpNet.socket(SctpNet.java:85) [:1.8.0_65]
        at sun.nio.ch.sctp.SctpServerChannelImpl.<init>(SctpServerChannelImpl.java:98) [:1.8.0_65]
        at com.sun.nio.sctp.SctpServerChannel.open(SctpServerChannel.java:102) [:1.8.0_65]
        at org.mobicents.protocols.sctp.ServerImpl.doInitSocketSctp(ServerImpl.java:178) [:1.7.8]
        at org.mobicents.protocols.sctp.ServerImpl.initSocket(ServerImpl.java:157) [:1.7.8]
        at org.mobicents.protocols.sctp.ServerImpl.start(ServerImpl.java:112) [:1.7.8]
        at org.mobicents.protocols.sctp.ManagementImpl.startServer(ManagementImpl.java:647) [:1.7.8]
        at org.mobicents.protocols.ss7.m3ua.impl.oam.SCTPShellExecutor.execute(SCTPShellExecutor.java:313) [:7.0.1383]
        at org.mobicents.ss7.management.console.ShellServer.perform(ShellServer.java:266) [:7.0.1383]
        at org.mobicents.protocols.ss7.scheduler.Task.run(Task.java:108) [:7.0.1383]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [:1.8.0_65]
        at java.lang.Thread.run(Thread.java:745) [:1.8.0_65]

**Comment by vetss** [comment]
Hi @javad272 

1) this question does not concern to JSS7 stack but more for SCTP stacj stuff and does not absolutely consern the problem of "GUI: adding of SCTP object modifying". Please avoid of adding of comments to any topic that is opened for some other case
You can also ask the problem at a public forum: 
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/mobicents-public/topics

2) your problem is like you have not installed libsctp lib or have some OS level problems with sctp lib
